config/routes.rb
Rails.application.routes.draw do

    root 'home#index'

    resources :artists do
      resources :arts, only: [:index], module: :artists
    end
    resources :arts

    resource :artist_sessions, only: [:create, :new, :destroy]

    resources :admin

    post "admin/accept_or_not", to: "admin#accept_or_not"

    resource :confirmation, only: [:show]

    resources :password_resets

end

app/models/artist.rb
class Artist < ActiveRecord::Base
    has_many :arts

    extend FriendlyId

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    VALID_BIRTHDAY_REGEX = /[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}/

    validates_presence_of :username, :email, :country, :birthday, :full_name
    validates_presence_of :about, allow_blank: true

    validates_length_of :username, minimum: 2

    validates_format_of :email, with: VALID_EMAIL_REGEX
    validates_format_of :birthday, with: VALID_BIRTHDAY_REGEX

    validates_uniqueness_of :username
    validates_uniqueness_of :email

    validates :password, :presence => true, :confirmation => true, length: {minimum: 4}, :if => :password

    has_secure_password

    validate :date_of_birthday

    has_attached_file :photo, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

    friendly_id :username, use: [:slugged, :history]

    before_create do |artist|
        artist.confirmation_token = SecureRandom.urlsafe_base64
    end

    def confirm!
        return if confirmed_at.present?

        self.confirmed_at = Time.current
        self.confirmation_token = ''

        save!
    end

    def date_of_birthday
        if self.birthday
            begin
                Date.parse(self.birthday)

                if self.birthday.to_date < 18.years.ago.to_date
                    errors.add(:birthday, "Você tem que ter menos de 18 anos.")
                elsif self.birthday.to_date > 13.years.ago.to_date
                    errors.add(:birthday, "Você tem que ter mais de 13 anos.")
                end
            rescue
                errors.add(:birthday, "Insira uma data correta.")
            end
        end
    end

    def self.authenticate(username_or_email, password)
        artist = find_by(username: username_or_email) || find_by(email: username_or_email)

        if artist.present?
            artist.authenticate(password)
        end
    end

    def custom_update_attributes(params)
        if params[:password].blank?
            params.delete :password
            params.delete :password_confirmation
            update_attributes params
        end
  end

    def send_password_reset
        generate_token(:password_reset_token)
        self.password_reset_sent_at = Time.current

        save

        PasswordResetMailer.password_reset(self).deliver
    end

    def generate_token(column)
        begin
            self[column] = SecureRandom.urlsafe_base64
        end while Artist.exists?(column => self[column])
    end
end

app/controllers/artists/my_arts_controller.rb
class Artists::MyArtsController < ApplicationController
    def index
        if params[:q].blank?
            artist = Artist.friendly.find(params[:artist_id])
            @artist_arts = artist.arts.all.order("created_at DESC")
        else
            @search = params[:q]
            artist = Artist.friendly.find(params[:artist_id])
            arts_searched = artist.arts.search(@search)
            @artist_arts = arts_searched.all.order("created_at DESC").page(params[:page]).per(9)
        end

    end

    private

    def can_see_my_arts
        unless artist_signed_in? && current_artist == artist
            redirect_to root_path, alert: "Você não têm acesso!"
        end
    end

    def artist
        @artist ||= artist.friendly.find(params[:artist_id])
    end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

    before_action :can_change, only: [:edit, :update]

    before_action :require_no_authentication_artist, only: [:new, :create]

    def new
        @artist = Artist.new
    end

    def create
        @artist = Artist.new(artist_params)

        if @artist.save
            Signup.confirm_email(@artist).deliver
            redirect_to @artist, notice: "Artista cadastrado com sucesso!"
        else
            render action: :new
        end
    end

    def show
        @artist = Artist.friendly.find(params[:id])

        if params[:q].blank?
            @artist = Artist.friendly.find(params[:id])
            @artist_arts = artist.arts.all.order("created_at DESC")
        else
            @search = params[:q]
            @artist = Artist.friendly.find(params[:id])
            arts_searched = artist.arts.search(@search)
            @artist_arts = arts_searched.all.order("created_at DESC").page(params[:page]).per(9)
        end
    end

    def edit
        @artist = Artist.friendly.find(params[:id])
    end

    def update
        @artist = Artist.friendly.find(params[:id])

        if @artist.custom_update_attributes(artist_params)
            redirect_to @artist, notice: "Artista editado com sucesso!"
        else
            render action: :edit
        end
    end

    private

    def artist_params
        params.require(:artist).permit(:username, :full_name, :email, :country, :about, :birthday, :password, :password_confirmation, :photo)
    end

    def can_change
        unless artist_signed_in? && current_artist == artist
            redirect_to artist_path(params[:id])
        end
    end

    def artist
        @artist ||= Artist.friendly.find(params[:id])
    end
end

app/views/artists/_css_cadastro.html.erb
<style>
textarea {
    width: 377px ; 
    font-size: 18px;
    padding: 8px 0px;
    text-align:center;  
    font-family: 'Raleway', sans-serif;
    margin-top:20px;
    background:#eaeaea;
    color:#484848;
    border:0;
    -webkit-transition: all 0.2s ease;
    -moz-transition: all 0.2s ease;
    -ms-transition: all 0.2s ease;
    -o-transition: all 0.2s ease;
    transition: all 0.2s ease;
}


textarea{
    height:130px;
}

textarea:focus{
    outline: 0;
    border:2px solid #989898;
    width:410px;
}

input,
label,
textarea {
display: block;
}

.erro {
color: black;
font-size: 1.3em;
font-weight: bold;
text-align: center;
font-weight: bold;
}

.sucesso {
color: red;
font-size: 2em;
}
::-webkit-input-placeholder {
  position: relative;
  -webkit-transform: translate(0, 0);
  transition: all 0.2s ease-in-out;
}

::-webkit-input-placeholder:hover{
cursor:text;
}

::-webkit-input-placeholder[style*=hidden] {
  font-weight: 700;
  font-size: 0.65em;
  -webkit-transform: translate(0, -1.65em);
  opacity: 1;
  visibility: visible !important;
  width:400px;
}



::-webkit-input-placeholder {
background:#eaeaea;
color:#484848;
}

:-moz-placeholder { /* Firefox 18- */

background:#eaeaea;
color:#484848;
}

::-moz-placeholder { /* Firefox 19+ */

background:#eaeaea;
color:#484848;
}

:-ms-input-placeholder {

background:#eaeaea;
color:#484848;
}

input:-webkit-autofill {
-webkit-box-shadow: 0 0 0 1000px #eaeaea inset;
color:#484848 !important;
}

.que_bom{
margin-top:20px;
font-size:2.5em;
}


button{
margin-top: 10px;
width:105px;
color:#484848;
padding:10px;
text-align:center;
cursor:pointer;
-webkit-transition: all 3.2s ease;
-moz-transition: all 3.2s ease;
-ms-transition: all 3.2s ease;
-o-transition: all 3.2s ease;
transition: all 3.2s ease;
border:0;
}
button:hover{
background:black;
color:white;
}

textarea{
resize:none;
}

a{
text-decoration: none;
color:white;
}

.go {
font-size: 20px;
cursor: pointer;
background-color:#eaeaea;
width:160px;
height:60px;
color:#484848;
border:1px solid #484848;
}

input,
label,
textarea {
display: block;
}

.erro {
color: black;
text-align: center;
font-weight: bold;
}

.sucesso {
color: red;
font-size: 2em;
}
::-webkit-input-placeholder {
  position: relative;
  -webkit-transform: translate(0, 0);
  transition: all 0.2s ease-in-out;
}

::-webkit-input-placeholder:hover{
cursor:text;
}

::-webkit-input-placeholder[style*=hidden] {
  font-weight: 700;
  font-size: 0.65em;
  -webkit-transform: translate(0, -1.65em);
  opacity: 1;
  visibility: visible !important;
  width:400px;
}
</style>

app/views/artists/_galeria.html.erb
<center>
    <%= form_tag artist_path, method: :get do %>
        <%= text_field_tag :q, @search, placeholder: "Ache alguma arte!", id: "search" %>
        <%= 
            button_tag(type: 'submit', class: "search-button-after") do 
            end 
        %>
    <% end %>
</center>

<% if @artist_arts.count == 0 %>
    <% if params[:q].blank? %>
        <p>Você não tem artes até o momento!</p>
    <% else %>
        <p>Não achamos nenhuma arte com o termo de pesquisa!</p>
    <% end %>
<% else %>
    <ol class="gallery_ol">
        <center><h4>Artes de <b><%= @artist.username %></b></h4></center>
        <% @artist_arts.each do |art| %>
            <li align="center" class="art_li">
                <div class="view view-fifth">
                    <%= link_to(image_tag(art.image.url(:medium), class: "art_img_src"), art_path(art)) %>
                    
                    <div class="mask">
                        <center>
                            <br>Did you like it?
                            <br>
                            <%= link_to("See more", art_path(art), style: "margin-top:15px;", class: "donate") %>
                            <div style="height:5px;"></div>
                        </center>

                        <%= link_to(image_tag(art.artist.photo.url(:medium), size: "41x41", class: 'img-author', style: "position:absolute;"), artist_path(art.artist)) %>

                        <%= link_to(content_tag(:p, "\"#{art.title}\"", class: "name-art", style: "position:absolute;"), art_path(art)) %>
                    </div>
                </div>
            </li>
        <% end %>
    </ol>
<% end %>

app/views/artists/edit.html.erb
<%= render 'css_cadastro' %>

<div class="hr"></div>
<div class='form' style="text-align:center;">

<style>
    .botoes {
        display: inline-block;
        margin-bottom: 10px;
        margin-left: 8px;
    }

    .editar {
        background-color: green;
        color: white;
    }

    .cancelar {
        color: black;
        background-color: gray;
        padding: 10px;
        text-decoration: none;
    }
</style>

<center>
    <div style="height:30px;"></div>

    <%= form_for @artist, :html => { :multipart => true }  do |f| %>
        <label>
            <%= f.text_field :username, id: "usernameLogin" %>
            <%= error_field @artist, :username %>
        </label>

        <label>
            <%= f.text_field :full_name, id: "usernameLogin" %>
            <%= error_field @artist, :full_name %>
        </label>

        <label>
            <%= f.text_field :email, id: "usernameLogin" %>
            <%= error_field @artist, :email %>
        </label>

        <%= f.file_field :photo %>

        <label>
            <%= f.text_area :about, placeholder: "Tell us about you! (optional)" %>
        </label>

        <label>
            <%= f.password_field :password, placeholder: "Type here your new password", id: "usernameLogin" %>
            <%= error_field @artist, :password %>
        </label>

        <label>
            <%= f.password_field :password_confirmation, placeholder: "Type here your new password again!", id: "usernameLogin" %>
            <%= error_field @artist, :password_confirmation %>
        </label>

        <p class='botoes cancelar'><a href="http://sharingdreams.co/gallery">Cancel</a></p>
        <%= f.submit "Atualizar!", class: 'botoes editar' %>
    <% end %>
</center>

app/views/artists/new.html.erb
<%= render 'css_cadastro' %>
<div class="hr"></div>
<div class='form' style="text-align:center;">
<center>
    <div class="que_bom">How nice your interest to join us!</div>

    <small class="forwhoRegister">Help kids around the world and be recognized! Sharing Dreams artists must have 13 years old or above and less than 18 years old.</small>

    <%= form_for @artist do |f| %>
        <label>
            <%= f.text_field :username, id: "usernameLogin", placeholder: "Create a username" %>
            <%= error_field @artist, :username %>
        </label>

        <label>
            <%= f.text_field :full_name, id: "usernameLogin", placeholder: "What's your name?" %>
            <%= error_field @artist, :full_name %>
        </label>

        <label>
            <%= f.text_field :email, placeholder: "Type here your email", id: "usernameLogin" %>
            <%= error_field @artist, :email %>
        </label>

        <label>
            <%= f.text_field :country, placeholder: "City, Country", id: "usernameLogin" %>
            <%= error_field @artist, :country %>
        </label>

        <label>
            <%= f.text_field :birthday, class: "birthday-date", id: "usernameLoginBirth", placeholder: "Birthday: mm/dd/yyyy" %>
            <%= error_field @artist, :birthday %>
        </label>

        <label>
            <%= f.text_area :about, placeholder: "Tell us about you! (optional)" %>
        </label>

        <label>
            <%= f.password_field :password, id: "usernameLogin", placeholder: "Type here your password" %>
            <%= error_field @artist, :password %>
        </label>

        <label>
            <%= f.password_field :password_confirmation, id: "usernameLogin", placeholder: "Type here your password again!" %>
            <%= error_field @artist, :password_confirmation %>
        </label>

        <div style="height:20px;"></div>

        <%= f.submit "Cadastrar!", class: "btn2 like" %>
        <div style="height:100px;"></div>
    <% end %>
</center>

</div>

app/views/artists/show.html.erb
<style>
	.capa {
		width:100%;
		background-color:#eee;
		text-align:center;
		display:inline-block;
		margin-top:-2px;
	}
	.about-me{
		font-size:12px;
		font-style:italic;
		font-family: Helvetica, Arial, 'lucida grande',tahoma,verdana,arial,sans-serif;
		padding-bottom:20px;
		text-align:center;
	}
	.city{
		font-size:15px;
	}
	@media(max-width: 329px){
		ul.menu_list{
			margin-left:-60px;
		}
		.logo_img{
			margin-left:0px !important;
		}
	}
</style>

<div class="hr"></div>
<div class="capa">
	<a href="#">
		<% if @artist.photo.present? %>
			<%= image_tag(@artist.photo.url(:medium), size: "150x150", class: "img_conta") %>
		<% else %>
			<%= image_tag("sem-foto.png", size: "150x150", class: "img_conta") %>
		<% end %>
	</a>
	<div class="txtg" style="margin-top:20px;"><%= @artist.username %></div>
	<div class="city"><%= @artist.country %></div>
		<p class="about-me">
			<%= @artist.about %>
		</p>
	</div>

	<div class="hr"></div>
				
	<div class="gallery">
		<div style="height:35px;"></div>
		<br> 
		<%= render 'galeria' %>       
	</div>	
	<div style="height:50px;"></div>