config/routes.rb
Rails.application.routes.draw do

    root 'home#index'

    resources :artists do
      resources :arts, only: [:index], module: :artists
    end
    resources :arts

    resource :artist_sessions, only: [:create, :new, :destroy]

    resources :admin

    post "admin/accept_or_not", to: "admin#accept_or_not"

    resource :confirmation, only: [:show]

    resources :password_resets

end

app/models/artist_session.rb
class ArtistSession
    include ActiveModel::Model

    attr_accessor :username_or_email, :password

    validates_presence_of :username_or_email, :password

    def initialize(session, attributes={})
        @session = session
        @username_or_email = attributes[:username_or_email]
        @password = attributes[:password]
    end

    def authenticate!
        artist = Artist.authenticate(@username_or_email, @password)

        if artist.present?
            store(artist)
        else
            errors.add(:base, :invalid_login)
            false
        end
    end

    def store(artist)
        @session[:artist_id] = artist.id
    end

    def current_artist
        Artist.find(@session[:artist_id])
    end

    def artist_signed_in?
        @session[:artist_id].present?
    end

    def destroy
        @session[:artist_id] = nil
    end

end

app/controllers/artist_sessions_controller.rb
class ArtistSessionsController < ApplicationController

    before_action :require_no_authentication_artist, only: [:new, :create]
    before_action :require_authentication_artist, only: [:destroy]

    def new
        @artist_session = ArtistSession.new(session)
    end

    def create
        @artist_session = ArtistSession.new(session, params[:artist_session])

        if @artist_session.authenticate!
            redirect_to root_path, notice: "Logado com sucesso!"
        else
            render :new
        end
    end

    def destroy
        artist_session.destroy
        redirect_to root_path, notice: "Logout realizado com sucesso!"
    end

end

app/views/artist_sessions/new.html.erb
<%= render 'artists/css_cadastro' %>

<div class="hr"></div>

<center>
    <span><strong>
    <% if @artist_session.errors.has_key? :base %>
        <%= @artist_session.errors[:base].join(', ') %>
    <% end %>
    </strong></span>

    <div class="txtg" style="margin-top:20px; color:#484848;">Login</div>

    <%= form_for @artist_session do |f| %>
        <fieldset class="fieldLogin">
            <label>
                <%= f.text_field :username_or_email, id: "usernameLogin", placeholder: "Username or email" %>
            </label>

            <label>
                <%= f.password_field :password, id: "passwordLogin", placeholder: "Password" %>
            </label>

            <%= f.submit "Login"%>
            </fieldset>
    <% end %>

    <p class="forgetpass">
        <%= link_to "Did you forget your password or your username? Click here!", new_password_reset_path, id: "preto" %>
    </p>
</center>