config/routes.rb
Rails.application.routes.draw do

    root 'home#index'

    resources :artists do
      resources :arts, only: [:index], module: :artists
    end
    resources :arts

    resource :artist_sessions, only: [:create, :new, :destroy]

    resources :admin

    post "admin/accept_or_not", to: "admin#accept_or_not"

    resource :confirmation, only: [:show]

    resources :password_resets

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Sharing Dreams</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />

        <script type="text/javascript">
            $(document).ready(function() {
              $('.birthday-date').datepicker({format: 'dd-mm-yyyy'});
            });
        </script>
    </head>

    <body>

        <% if notice.present? %>
            <p><%= notice %></p>
        <% end %>

        <% if alert.present? %>
            <p><%= alert %></p>
        <% end %>

        <div class="top">
            <div class="logo" id='logo-margin'>
                <%= link_to(image_tag('logo.png'), root_url, class: "logo_img") %>
            </div>
            <% if artist_signed_in? %>
                <ul class="menu_list" id='menu-margin'>
                    <li><%= link_to "Editar perfil", edit_artist_path(current_artist), id: "menu" %></li>
                    <li><%= link_to "Nova arte", new_art_path, id: "menu" %></li>
                     <li><%= link_to "Logout", artist_sessions_path, method: "delete", id: "menu" %></li>
                    <li>
                        <a href="#">
                            <% if current_artist.photo.present? %>
                                <%= link_to(image_tag(current_artist.photo.url(:medium), size: "50x50", class: 'perfil_img_menu', id: "img-ok", :style => "-webkit-border-radius:500; -moz-border-radius: 500px; border-radius: 500px; float:right; margin-top:-20px;"), artist_path(current_artist)) %>
                            <% else %>
                                <%= link_to(image_tag("sem-foto.png", size: "50x50", class: 'perfil_img_menu', id: "img-ok", :style => "-webkit-border-radius:500; -moz-border-radius: 500px; border-radius: 500px; float:right; margin-top:-20px;"), artist_path(current_artist)) %>
                            <% end %>
                      </a>
                    </li>
                </ul>
            <% else %>
                <ul class="menu_list" id='menu-margin'>
                    <li>
                        <%= link_to "About", root_path, id: "menu" %>
                    </li>
                    <li>
                        <%= link_to "Join", new_artist_path, id: "menu" %>
                    </li>
                    <li><%= link_to "Login", new_artist_sessions_path, id: "menu" %></li>
                </ul>
            <% end %>
        </div>

        <%= yield %>

    </body>

</html>